### ISSUE TITLE
Add more tests

### ISSUE THREAD

**Issue by decanus** [ensdomains/root#3]
- [x] Check that you can update the registrar for a domain if the proof changes (from valid proof a -> valid proof b, from no proof -> proof, and from proof -> no proof) **(Partially solved in https://github.com/ensdomains/root/pull/8)**
- [x] Check that you can't replace a custom registrar with the default one even if the TXT record proof has expired (but is still in the oracle). **(Solved in https://github.com/ensdomains/root/pull/9)**
- [x] Check that you can't use an expired TXT record to update the registrar address **(Solved in https://github.com/ensdomains/root/pull/6)**
- [x] Check that invalid TXT records are treated the same as nonexistent one (we don't want a name to be unavailable because it has an unexpected record).

**Comment by decanus** [comment]
@Arachnid do we really want to implement requirement 2 as it is specified here?

**Comment by Arachnid** [comment]
@deaneigenmann why would we not?

**Comment by decanus** [comment]
@Arachnid do we not consider that to no longer be a valid record and so we should move over to the default registrar?
